"""add_sync_change_reviews_and_faculty_dept_id

Revision ID: 1e9ea3f9a382
Revises: 479e6475fe18
Create Date: 2026-08-28 23:22:55.353371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9ea3f9a382'
down_revision: Union[str, Sequence[str], None] = '479e6475fe18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_change_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('previous_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['website_sync_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['website_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_change_reviews_created_at'), 'sync_change_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_change_reviews_history_id'), 'sync_change_reviews', ['history_id'], unique=False)
    op.create_index(op.f('ix_sync_change_reviews_id'), 'sync_change_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_sync_change_reviews_source_id'), 'sync_change_reviews', ['source_id'], unique=False)
    op.create_index(op.f('ix_sync_change_reviews_status'), 'sync_change_reviews', ['status'], unique=False)
    op.add_column('faculty', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_faculty_department_id'), 'faculty', ['department_id'], unique=False)
    op.create_foreign_key('fk_faculty_department_id_departments', 'faculty', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('website_sources', sa.Column('auto_sync_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('website_sources', sa.Column('next_scheduled_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_sources', 'next_scheduled_sync_at')
    op.drop_column('website_sources', 'auto_sync_enabled')
    op.drop_constraint('fk_faculty_department_id_departments', 'faculty', type_='foreignkey')

    op.drop_index(op.f('ix_faculty_department_id'), table_name='faculty')
    op.drop_column('faculty', 'department_id')
    op.drop_index(op.f('ix_sync_change_reviews_status'), table_name='sync_change_reviews')
    op.drop_index(op.f('ix_sync_change_reviews_source_id'), table_name='sync_change_reviews')
    op.drop_index(op.f('ix_sync_change_reviews_id'), table_name='sync_change_reviews')
    op.drop_index(op.f('ix_sync_change_reviews_history_id'), table_name='sync_change_reviews')
    op.drop_index(op.f('ix_sync_change_reviews_created_at'), table_name='sync_change_reviews')
    op.drop_table('sync_change_reviews')
    # ### end Alembic commands ###
