"""update website sources state string

Revision ID: 479e6475fe18
Revises: 3b5a8c24d678
Create Date: 2026-08-28 22:10:21.120160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '479e6475fe18'
down_revision: Union[str, Sequence[str], None] = '3b5a8c24d678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_calendar', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('announcements', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('college_info', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('departments', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_departments_source_hash'), 'departments', ['source_hash'], unique=False)
    op.alter_column('examinations', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('important_links', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('placements', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('website_sources', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'IDLE', 'SYNCING', 'ERROR', 'DISABLED', name='website_source_status'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('website_sync_history', sa.Column('invalid_url_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('website_sync_history', sa.Column('indexed_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('website_sync_history', 'status',
               existing_type=postgresql.ENUM('SUCCESS', 'FAILED', 'IN_PROGRESS', name='sync_status'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_sync_history', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('SUCCESS', 'FAILED', 'IN_PROGRESS', name='sync_status'),
               existing_nullable=False)
    op.drop_column('website_sync_history', 'indexed_count')
    op.drop_column('website_sync_history', 'invalid_url_count')
    op.alter_column('website_sources', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTIVE', 'IDLE', 'SYNCING', 'ERROR', 'DISABLED', name='website_source_status'),
               existing_nullable=False)
    op.alter_column('placements', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('important_links', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('examinations', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_departments_source_hash'), table_name='departments')
    op.alter_column('departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('departments', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('college_info', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('announcements', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('academic_calendar', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###

